# Generated by Django 4.1.3 on 2023-05-25 12:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alertgroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert', models.CharField(max_length=5)),
                ('user', models.ManyToManyField(blank=True, related_name='alertusers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
