# Generated by Django 4.1.3 on 2023-05-25 17:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('alerts', '0003_remove_alertgroup_user_alertgroup_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertgroup',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='alertusers', to=settings.AUTH_USER_MODEL),
        ),
    ]
