# Generated by Django 4.1.3 on 2023-06-07 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0004_alter_alertgroup_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertgroup',
            name='alert',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
